
version: "2"

services:
  server:
    image: docker.gitea.com/gitea:latest-rootless
    container_name: gitea
    logging:
      driver: journald
    userns_mode: "keep-id:uid=1000,gid=1000"
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"