version: "3.8"
services:
  n8n:
    logging:
      driver: journald
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - GENERIC_TIMEZONE=$(timedatectl show --value --property=Timezone)
      - TZ=$(timedatectl show --value --property=Timezone)
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
