version: "3.8"
services:
  portainer_agent:
    image: portainer/agent:2.33.6
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - SOURCE_SOCKET:/var/run/docker.sock
